// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/article.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.model;

public final class ArticleProto {
  private ArticleProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ArticleProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArticleResourcePathOrBuilder extends
      // @@protoc_insertion_point(interface_extends:article.ArticleResourcePath)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * 图片URL/路径
     * </pre>
     *
     * <code>string image = 2;</code>
     * @return The image.
     */
    java.lang.String getImage();
    /**
     * <pre>
     * 图片URL/路径
     * </pre>
     *
     * <code>string image = 2;</code>
     * @return The bytes for image.
     */
    com.google.protobuf.ByteString
        getImageBytes();

    /**
     * <pre>
     * Markdown内容
     * </pre>
     *
     * <code>string md = 3;</code>
     * @return The md.
     */
    java.lang.String getMd();
    /**
     * <pre>
     * Markdown内容
     * </pre>
     *
     * <code>string md = 3;</code>
     * @return The bytes for md.
     */
    com.google.protobuf.ByteString
        getMdBytes();

    /**
     * <pre>
     * 作者
     * </pre>
     *
     * <code>string author = 4;</code>
     * @return The author.
     */
    java.lang.String getAuthor();
    /**
     * <pre>
     * 作者
     * </pre>
     *
     * <code>string author = 4;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 5;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 5;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 6;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 6;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 7;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 7;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * 邮箱
     * </pre>
     *
     * <code>string email = 8;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <pre>
     * 邮箱
     * </pre>
     *
     * <code>string email = 8;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <pre>
     * 点赞数
     * </pre>
     *
     * <code>int64 like = 9;</code>
     * @return The like.
     */
    long getLike();

    /**
     * <pre>
     * 评论数
     * </pre>
     *
     * <code>int64 comment = 10;</code>
     * @return The comment.
     */
    long getComment();

    /**
     * <pre>
     * 浏览数
     * </pre>
     *
     * <code>int64 browse = 11;</code>
     * @return The browse.
     */
    long getBrowse();
  }
  /**
   * Protobuf type {@code article.ArticleResourcePath}
   */
  public static final class ArticleResourcePath extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:article.ArticleResourcePath)
      ArticleResourcePathOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ArticleResourcePath.class.getName());
    }
    // Use ArticleResourcePath.newBuilder() to construct.
    private ArticleResourcePath(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ArticleResourcePath() {
      image_ = "";
      md_ = "";
      author_ = "";
      title_ = "";
      label_ = "";
      description_ = "";
      email_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.model.ArticleProto.internal_static_article_ArticleResourcePath_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.model.ArticleProto.internal_static_article_ArticleResourcePath_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.model.ArticleProto.ArticleResourcePath.class, com.example.demo.model.ArticleProto.ArticleResourcePath.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IMAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object image_ = "";
    /**
     * <pre>
     * 图片URL/路径
     * </pre>
     *
     * <code>string image = 2;</code>
     * @return The image.
     */
    @java.lang.Override
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 图片URL/路径
     * </pre>
     *
     * <code>string image = 2;</code>
     * @return The bytes for image.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MD_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object md_ = "";
    /**
     * <pre>
     * Markdown内容
     * </pre>
     *
     * <code>string md = 3;</code>
     * @return The md.
     */
    @java.lang.Override
    public java.lang.String getMd() {
      java.lang.Object ref = md_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        md_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Markdown内容
     * </pre>
     *
     * <code>string md = 3;</code>
     * @return The bytes for md.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMdBytes() {
      java.lang.Object ref = md_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object author_ = "";
    /**
     * <pre>
     * 作者
     * </pre>
     *
     * <code>string author = 4;</code>
     * @return The author.
     */
    @java.lang.Override
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 作者
     * </pre>
     *
     * <code>string author = 4;</code>
     * @return The bytes for author.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 5;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 5;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object label_ = "";
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 6;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>string label = 6;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 7;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 7;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <pre>
     * 邮箱
     * </pre>
     *
     * <code>string email = 8;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 邮箱
     * </pre>
     *
     * <code>string email = 8;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKE_FIELD_NUMBER = 9;
    private long like_ = 0L;
    /**
     * <pre>
     * 点赞数
     * </pre>
     *
     * <code>int64 like = 9;</code>
     * @return The like.
     */
    @java.lang.Override
    public long getLike() {
      return like_;
    }

    public static final int COMMENT_FIELD_NUMBER = 10;
    private long comment_ = 0L;
    /**
     * <pre>
     * 评论数
     * </pre>
     *
     * <code>int64 comment = 10;</code>
     * @return The comment.
     */
    @java.lang.Override
    public long getComment() {
      return comment_;
    }

    public static final int BROWSE_FIELD_NUMBER = 11;
    private long browse_ = 0L;
    /**
     * <pre>
     * 浏览数
     * </pre>
     *
     * <code>int64 browse = 11;</code>
     * @return The browse.
     */
    @java.lang.Override
    public long getBrowse() {
      return browse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(image_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, image_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(md_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, md_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(author_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, author_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, label_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, email_);
      }
      if (like_ != 0L) {
        output.writeInt64(9, like_);
      }
      if (comment_ != 0L) {
        output.writeInt64(10, comment_);
      }
      if (browse_ != 0L) {
        output.writeInt64(11, browse_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(image_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, image_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(md_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, md_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(author_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, author_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, label_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, email_);
      }
      if (like_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, like_);
      }
      if (comment_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, comment_);
      }
      if (browse_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, browse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.model.ArticleProto.ArticleResourcePath)) {
        return super.equals(obj);
      }
      com.example.demo.model.ArticleProto.ArticleResourcePath other = (com.example.demo.model.ArticleProto.ArticleResourcePath) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getImage()
          .equals(other.getImage())) return false;
      if (!getMd()
          .equals(other.getMd())) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getLabel()
          .equals(other.getLabel())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (getLike()
          != other.getLike()) return false;
      if (getComment()
          != other.getComment()) return false;
      if (getBrowse()
          != other.getBrowse()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (37 * hash) + MD_FIELD_NUMBER;
      hash = (53 * hash) + getMd().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + LIKE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLike());
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getComment());
      hash = (37 * hash) + BROWSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBrowse());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.model.ArticleProto.ArticleResourcePath parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.model.ArticleProto.ArticleResourcePath prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code article.ArticleResourcePath}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:article.ArticleResourcePath)
        com.example.demo.model.ArticleProto.ArticleResourcePathOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.model.ArticleProto.internal_static_article_ArticleResourcePath_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.model.ArticleProto.internal_static_article_ArticleResourcePath_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.model.ArticleProto.ArticleResourcePath.class, com.example.demo.model.ArticleProto.ArticleResourcePath.Builder.class);
      }

      // Construct using com.example.demo.model.ArticleProto.ArticleResourcePath.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        image_ = "";
        md_ = "";
        author_ = "";
        title_ = "";
        label_ = "";
        description_ = "";
        email_ = "";
        like_ = 0L;
        comment_ = 0L;
        browse_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.model.ArticleProto.internal_static_article_ArticleResourcePath_descriptor;
      }

      @java.lang.Override
      public com.example.demo.model.ArticleProto.ArticleResourcePath getDefaultInstanceForType() {
        return com.example.demo.model.ArticleProto.ArticleResourcePath.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.model.ArticleProto.ArticleResourcePath build() {
        com.example.demo.model.ArticleProto.ArticleResourcePath result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.model.ArticleProto.ArticleResourcePath buildPartial() {
        com.example.demo.model.ArticleProto.ArticleResourcePath result = new com.example.demo.model.ArticleProto.ArticleResourcePath(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.demo.model.ArticleProto.ArticleResourcePath result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.image_ = image_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.md_ = md_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.author_ = author_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.label_ = label_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.like_ = like_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.comment_ = comment_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.browse_ = browse_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.model.ArticleProto.ArticleResourcePath) {
          return mergeFrom((com.example.demo.model.ArticleProto.ArticleResourcePath)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.model.ArticleProto.ArticleResourcePath other) {
        if (other == com.example.demo.model.ArticleProto.ArticleResourcePath.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getImage().isEmpty()) {
          image_ = other.image_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMd().isEmpty()) {
          md_ = other.md_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.getLike() != 0L) {
          setLike(other.getLike());
        }
        if (other.getComment() != 0L) {
          setComment(other.getComment());
        }
        if (other.getBrowse() != 0L) {
          setBrowse(other.getBrowse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                image_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                md_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                author_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                label_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 72: {
                like_ = input.readInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                comment_ = input.readInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                browse_ = input.readInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object image_ = "";
      /**
       * <pre>
       * 图片URL/路径
       * </pre>
       *
       * <code>string image = 2;</code>
       * @return The image.
       */
      public java.lang.String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 图片URL/路径
       * </pre>
       *
       * <code>string image = 2;</code>
       * @return The bytes for image.
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        java.lang.Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 图片URL/路径
       * </pre>
       *
       * <code>string image = 2;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        image_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片URL/路径
       * </pre>
       *
       * <code>string image = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        image_ = getDefaultInstance().getImage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片URL/路径
       * </pre>
       *
       * <code>string image = 2;</code>
       * @param value The bytes for image to set.
       * @return This builder for chaining.
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        image_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object md_ = "";
      /**
       * <pre>
       * Markdown内容
       * </pre>
       *
       * <code>string md = 3;</code>
       * @return The md.
       */
      public java.lang.String getMd() {
        java.lang.Object ref = md_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          md_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Markdown内容
       * </pre>
       *
       * <code>string md = 3;</code>
       * @return The bytes for md.
       */
      public com.google.protobuf.ByteString
          getMdBytes() {
        java.lang.Object ref = md_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Markdown内容
       * </pre>
       *
       * <code>string md = 3;</code>
       * @param value The md to set.
       * @return This builder for chaining.
       */
      public Builder setMd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        md_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Markdown内容
       * </pre>
       *
       * <code>string md = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMd() {
        md_ = getDefaultInstance().getMd();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Markdown内容
       * </pre>
       *
       * <code>string md = 3;</code>
       * @param value The bytes for md to set.
       * @return This builder for chaining.
       */
      public Builder setMdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        md_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <pre>
       * 作者
       * </pre>
       *
       * <code>string author = 4;</code>
       * @return The author.
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 作者
       * </pre>
       *
       * <code>string author = 4;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 作者
       * </pre>
       *
       * <code>string author = 4;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        author_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作者
       * </pre>
       *
       * <code>string author = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        author_ = getDefaultInstance().getAuthor();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作者
       * </pre>
       *
       * <code>string author = 4;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        author_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 5;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 5;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 5;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标题
       * </pre>
       *
       * <code>string title = 5;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 6;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 6;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 6;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        label_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        label_ = getDefaultInstance().getLabel();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签
       * </pre>
       *
       * <code>string label = 6;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        label_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 7;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 7;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 7;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string description = 7;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <pre>
       * 邮箱
       * </pre>
       *
       * <code>string email = 8;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 邮箱
       * </pre>
       *
       * <code>string email = 8;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 邮箱
       * </pre>
       *
       * <code>string email = 8;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 邮箱
       * </pre>
       *
       * <code>string email = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 邮箱
       * </pre>
       *
       * <code>string email = 8;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private long like_ ;
      /**
       * <pre>
       * 点赞数
       * </pre>
       *
       * <code>int64 like = 9;</code>
       * @return The like.
       */
      @java.lang.Override
      public long getLike() {
        return like_;
      }
      /**
       * <pre>
       * 点赞数
       * </pre>
       *
       * <code>int64 like = 9;</code>
       * @param value The like to set.
       * @return This builder for chaining.
       */
      public Builder setLike(long value) {

        like_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 点赞数
       * </pre>
       *
       * <code>int64 like = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLike() {
        bitField0_ = (bitField0_ & ~0x00000100);
        like_ = 0L;
        onChanged();
        return this;
      }

      private long comment_ ;
      /**
       * <pre>
       * 评论数
       * </pre>
       *
       * <code>int64 comment = 10;</code>
       * @return The comment.
       */
      @java.lang.Override
      public long getComment() {
        return comment_;
      }
      /**
       * <pre>
       * 评论数
       * </pre>
       *
       * <code>int64 comment = 10;</code>
       * @param value The comment to set.
       * @return This builder for chaining.
       */
      public Builder setComment(long value) {

        comment_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 评论数
       * </pre>
       *
       * <code>int64 comment = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000200);
        comment_ = 0L;
        onChanged();
        return this;
      }

      private long browse_ ;
      /**
       * <pre>
       * 浏览数
       * </pre>
       *
       * <code>int64 browse = 11;</code>
       * @return The browse.
       */
      @java.lang.Override
      public long getBrowse() {
        return browse_;
      }
      /**
       * <pre>
       * 浏览数
       * </pre>
       *
       * <code>int64 browse = 11;</code>
       * @param value The browse to set.
       * @return This builder for chaining.
       */
      public Builder setBrowse(long value) {

        browse_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 浏览数
       * </pre>
       *
       * <code>int64 browse = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrowse() {
        bitField0_ = (bitField0_ & ~0x00000400);
        browse_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:article.ArticleResourcePath)
    }

    // @@protoc_insertion_point(class_scope:article.ArticleResourcePath)
    private static final com.example.demo.model.ArticleProto.ArticleResourcePath DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.model.ArticleProto.ArticleResourcePath();
    }

    public static com.example.demo.model.ArticleProto.ArticleResourcePath getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArticleResourcePath>
        PARSER = new com.google.protobuf.AbstractParser<ArticleResourcePath>() {
      @java.lang.Override
      public ArticleResourcePath parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ArticleResourcePath> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArticleResourcePath> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.model.ArticleProto.ArticleResourcePath getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_article_ArticleResourcePath_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_article_ArticleResourcePath_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/article.proto\022\007article\"" +
      "\304\001\n\023ArticleResourcePath\022\021\n\ttimestamp\030\001 \001" +
      "(\003\022\r\n\005image\030\002 \001(\t\022\n\n\002md\030\003 \001(\t\022\016\n\006author\030" +
      "\004 \001(\t\022\r\n\005title\030\005 \001(\t\022\r\n\005label\030\006 \001(\t\022\023\n\013d" +
      "escription\030\007 \001(\t\022\r\n\005email\030\010 \001(\t\022\014\n\004like\030" +
      "\t \001(\003\022\017\n\007comment\030\n \001(\003\022\016\n\006browse\030\013 \001(\003B&" +
      "\n\026com.example.demo.modelB\014ArticleProtob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_article_ArticleResourcePath_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_article_ArticleResourcePath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_article_ArticleResourcePath_descriptor,
        new java.lang.String[] { "Timestamp", "Image", "Md", "Author", "Title", "Label", "Description", "Email", "Like", "Comment", "Browse", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
