// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: musicInfo.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protomodel;

public final class MusicProto {
  private MusicProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MusicProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MusicInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:music.MusicInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 建议蛇形命名
     * </pre>
     *
     * <code>string artists_name = 3;</code>
     * @return The artistsName.
     */
    java.lang.String getArtistsName();
    /**
     * <pre>
     * 建议蛇形命名
     * </pre>
     *
     * <code>string artists_name = 3;</code>
     * @return The bytes for artistsName.
     */
    com.google.protobuf.ByteString
        getArtistsNameBytes();

    /**
     * <code>string picurl = 4;</code>
     * @return The picurl.
     */
    java.lang.String getPicurl();
    /**
     * <code>string picurl = 4;</code>
     * @return The bytes for picurl.
     */
    com.google.protobuf.ByteString
        getPicurlBytes();

    /**
     * <pre>
     * 若存毫秒，建议改为 int64
     * </pre>
     *
     * <code>string music_duration = 5;</code>
     * @return The musicDuration.
     */
    java.lang.String getMusicDuration();
    /**
     * <pre>
     * 若存毫秒，建议改为 int64
     * </pre>
     *
     * <code>string music_duration = 5;</code>
     * @return The bytes for musicDuration.
     */
    com.google.protobuf.ByteString
        getMusicDurationBytes();
  }
  /**
   * <pre>
   * 单条音乐信息
   * </pre>
   *
   * Protobuf type {@code music.MusicInfo}
   */
  public static final class MusicInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:music.MusicInfo)
      MusicInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MusicInfo.class.getName());
    }
    // Use MusicInfo.newBuilder() to construct.
    private MusicInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MusicInfo() {
      id_ = "";
      name_ = "";
      artistsName_ = "";
      picurl_ = "";
      musicDuration_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protomodel.MusicProto.MusicInfo.class, com.example.demo.protomodel.MusicProto.MusicInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARTISTS_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object artistsName_ = "";
    /**
     * <pre>
     * 建议蛇形命名
     * </pre>
     *
     * <code>string artists_name = 3;</code>
     * @return The artistsName.
     */
    @java.lang.Override
    public java.lang.String getArtistsName() {
      java.lang.Object ref = artistsName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        artistsName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 建议蛇形命名
     * </pre>
     *
     * <code>string artists_name = 3;</code>
     * @return The bytes for artistsName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArtistsNameBytes() {
      java.lang.Object ref = artistsName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artistsName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICURL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object picurl_ = "";
    /**
     * <code>string picurl = 4;</code>
     * @return The picurl.
     */
    @java.lang.Override
    public java.lang.String getPicurl() {
      java.lang.Object ref = picurl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picurl_ = s;
        return s;
      }
    }
    /**
     * <code>string picurl = 4;</code>
     * @return The bytes for picurl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPicurlBytes() {
      java.lang.Object ref = picurl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUSIC_DURATION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object musicDuration_ = "";
    /**
     * <pre>
     * 若存毫秒，建议改为 int64
     * </pre>
     *
     * <code>string music_duration = 5;</code>
     * @return The musicDuration.
     */
    @java.lang.Override
    public java.lang.String getMusicDuration() {
      java.lang.Object ref = musicDuration_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        musicDuration_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 若存毫秒，建议改为 int64
     * </pre>
     *
     * <code>string music_duration = 5;</code>
     * @return The bytes for musicDuration.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMusicDurationBytes() {
      java.lang.Object ref = musicDuration_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        musicDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(artistsName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, artistsName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(picurl_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, picurl_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(musicDuration_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, musicDuration_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(artistsName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, artistsName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(picurl_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, picurl_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(musicDuration_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, musicDuration_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.protomodel.MusicProto.MusicInfo)) {
        return super.equals(obj);
      }
      com.example.demo.protomodel.MusicProto.MusicInfo other = (com.example.demo.protomodel.MusicProto.MusicInfo) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getArtistsName()
          .equals(other.getArtistsName())) return false;
      if (!getPicurl()
          .equals(other.getPicurl())) return false;
      if (!getMusicDuration()
          .equals(other.getMusicDuration())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ARTISTS_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getArtistsName().hashCode();
      hash = (37 * hash) + PICURL_FIELD_NUMBER;
      hash = (53 * hash) + getPicurl().hashCode();
      hash = (37 * hash) + MUSIC_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getMusicDuration().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.protomodel.MusicProto.MusicInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 单条音乐信息
     * </pre>
     *
     * Protobuf type {@code music.MusicInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:music.MusicInfo)
        com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.protomodel.MusicProto.MusicInfo.class, com.example.demo.protomodel.MusicProto.MusicInfo.Builder.class);
      }

      // Construct using com.example.demo.protomodel.MusicProto.MusicInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        name_ = "";
        artistsName_ = "";
        picurl_ = "";
        musicDuration_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfo_descriptor;
      }

      @java.lang.Override
      public com.example.demo.protomodel.MusicProto.MusicInfo getDefaultInstanceForType() {
        return com.example.demo.protomodel.MusicProto.MusicInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.protomodel.MusicProto.MusicInfo build() {
        com.example.demo.protomodel.MusicProto.MusicInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.protomodel.MusicProto.MusicInfo buildPartial() {
        com.example.demo.protomodel.MusicProto.MusicInfo result = new com.example.demo.protomodel.MusicProto.MusicInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.demo.protomodel.MusicProto.MusicInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.artistsName_ = artistsName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.picurl_ = picurl_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.musicDuration_ = musicDuration_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.protomodel.MusicProto.MusicInfo) {
          return mergeFrom((com.example.demo.protomodel.MusicProto.MusicInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.protomodel.MusicProto.MusicInfo other) {
        if (other == com.example.demo.protomodel.MusicProto.MusicInfo.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getArtistsName().isEmpty()) {
          artistsName_ = other.artistsName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPicurl().isEmpty()) {
          picurl_ = other.picurl_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getMusicDuration().isEmpty()) {
          musicDuration_ = other.musicDuration_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                artistsName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                picurl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                musicDuration_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object artistsName_ = "";
      /**
       * <pre>
       * 建议蛇形命名
       * </pre>
       *
       * <code>string artists_name = 3;</code>
       * @return The artistsName.
       */
      public java.lang.String getArtistsName() {
        java.lang.Object ref = artistsName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          artistsName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 建议蛇形命名
       * </pre>
       *
       * <code>string artists_name = 3;</code>
       * @return The bytes for artistsName.
       */
      public com.google.protobuf.ByteString
          getArtistsNameBytes() {
        java.lang.Object ref = artistsName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          artistsName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 建议蛇形命名
       * </pre>
       *
       * <code>string artists_name = 3;</code>
       * @param value The artistsName to set.
       * @return This builder for chaining.
       */
      public Builder setArtistsName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        artistsName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建议蛇形命名
       * </pre>
       *
       * <code>string artists_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearArtistsName() {
        artistsName_ = getDefaultInstance().getArtistsName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建议蛇形命名
       * </pre>
       *
       * <code>string artists_name = 3;</code>
       * @param value The bytes for artistsName to set.
       * @return This builder for chaining.
       */
      public Builder setArtistsNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        artistsName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object picurl_ = "";
      /**
       * <code>string picurl = 4;</code>
       * @return The picurl.
       */
      public java.lang.String getPicurl() {
        java.lang.Object ref = picurl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          picurl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string picurl = 4;</code>
       * @return The bytes for picurl.
       */
      public com.google.protobuf.ByteString
          getPicurlBytes() {
        java.lang.Object ref = picurl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          picurl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string picurl = 4;</code>
       * @param value The picurl to set.
       * @return This builder for chaining.
       */
      public Builder setPicurl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        picurl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string picurl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPicurl() {
        picurl_ = getDefaultInstance().getPicurl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string picurl = 4;</code>
       * @param value The bytes for picurl to set.
       * @return This builder for chaining.
       */
      public Builder setPicurlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        picurl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object musicDuration_ = "";
      /**
       * <pre>
       * 若存毫秒，建议改为 int64
       * </pre>
       *
       * <code>string music_duration = 5;</code>
       * @return The musicDuration.
       */
      public java.lang.String getMusicDuration() {
        java.lang.Object ref = musicDuration_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          musicDuration_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 若存毫秒，建议改为 int64
       * </pre>
       *
       * <code>string music_duration = 5;</code>
       * @return The bytes for musicDuration.
       */
      public com.google.protobuf.ByteString
          getMusicDurationBytes() {
        java.lang.Object ref = musicDuration_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          musicDuration_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 若存毫秒，建议改为 int64
       * </pre>
       *
       * <code>string music_duration = 5;</code>
       * @param value The musicDuration to set.
       * @return This builder for chaining.
       */
      public Builder setMusicDuration(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        musicDuration_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 若存毫秒，建议改为 int64
       * </pre>
       *
       * <code>string music_duration = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMusicDuration() {
        musicDuration_ = getDefaultInstance().getMusicDuration();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 若存毫秒，建议改为 int64
       * </pre>
       *
       * <code>string music_duration = 5;</code>
       * @param value The bytes for musicDuration to set.
       * @return This builder for chaining.
       */
      public Builder setMusicDurationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        musicDuration_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:music.MusicInfo)
    }

    // @@protoc_insertion_point(class_scope:music.MusicInfo)
    private static final com.example.demo.protomodel.MusicProto.MusicInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.protomodel.MusicProto.MusicInfo();
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MusicInfo>
        PARSER = new com.google.protobuf.AbstractParser<MusicInfo>() {
      @java.lang.Override
      public MusicInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MusicInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MusicInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.protomodel.MusicProto.MusicInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MusicInfoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:music.MusicInfoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    java.util.List<com.example.demo.protomodel.MusicProto.MusicInfo> 
        getItemsList();
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    com.example.demo.protomodel.MusicProto.MusicInfo getItems(int index);
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    java.util.List<? extends com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * ✅ 仅用于返回列表（无 total / page / page_size）
   * </pre>
   *
   * Protobuf type {@code music.MusicInfoList}
   */
  public static final class MusicInfoList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:music.MusicInfoList)
      MusicInfoListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MusicInfoList.class.getName());
    }
    // Use MusicInfoList.newBuilder() to construct.
    private MusicInfoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MusicInfoList() {
      items_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protomodel.MusicProto.MusicInfoList.class, com.example.demo.protomodel.MusicProto.MusicInfoList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.example.demo.protomodel.MusicProto.MusicInfo> items_;
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.demo.protomodel.MusicProto.MusicInfo> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    @java.lang.Override
    public com.example.demo.protomodel.MusicProto.MusicInfo getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .music.MusicInfo items = 1;</code>
     */
    @java.lang.Override
    public com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.protomodel.MusicProto.MusicInfoList)) {
        return super.equals(obj);
      }
      com.example.demo.protomodel.MusicProto.MusicInfoList other = (com.example.demo.protomodel.MusicProto.MusicInfoList) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.protomodel.MusicProto.MusicInfoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.protomodel.MusicProto.MusicInfoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ✅ 仅用于返回列表（无 total / page / page_size）
     * </pre>
     *
     * Protobuf type {@code music.MusicInfoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:music.MusicInfoList)
        com.example.demo.protomodel.MusicProto.MusicInfoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfoList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.protomodel.MusicProto.MusicInfoList.class, com.example.demo.protomodel.MusicProto.MusicInfoList.Builder.class);
      }

      // Construct using com.example.demo.protomodel.MusicProto.MusicInfoList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.protomodel.MusicProto.internal_static_music_MusicInfoList_descriptor;
      }

      @java.lang.Override
      public com.example.demo.protomodel.MusicProto.MusicInfoList getDefaultInstanceForType() {
        return com.example.demo.protomodel.MusicProto.MusicInfoList.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.protomodel.MusicProto.MusicInfoList build() {
        com.example.demo.protomodel.MusicProto.MusicInfoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.protomodel.MusicProto.MusicInfoList buildPartial() {
        com.example.demo.protomodel.MusicProto.MusicInfoList result = new com.example.demo.protomodel.MusicProto.MusicInfoList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.demo.protomodel.MusicProto.MusicInfoList result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(com.example.demo.protomodel.MusicProto.MusicInfoList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.protomodel.MusicProto.MusicInfoList) {
          return mergeFrom((com.example.demo.protomodel.MusicProto.MusicInfoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.protomodel.MusicProto.MusicInfoList other) {
        if (other == com.example.demo.protomodel.MusicProto.MusicInfoList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.demo.protomodel.MusicProto.MusicInfo m =
                    input.readMessage(
                        com.example.demo.protomodel.MusicProto.MusicInfo.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.demo.protomodel.MusicProto.MusicInfo> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.example.demo.protomodel.MusicProto.MusicInfo>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.demo.protomodel.MusicProto.MusicInfo, com.example.demo.protomodel.MusicProto.MusicInfo.Builder, com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public java.util.List<com.example.demo.protomodel.MusicProto.MusicInfo> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public com.example.demo.protomodel.MusicProto.MusicInfo getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder setItems(
          int index, com.example.demo.protomodel.MusicProto.MusicInfo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder setItems(
          int index, com.example.demo.protomodel.MusicProto.MusicInfo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder addItems(com.example.demo.protomodel.MusicProto.MusicInfo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder addItems(
          int index, com.example.demo.protomodel.MusicProto.MusicInfo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder addItems(
          com.example.demo.protomodel.MusicProto.MusicInfo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder addItems(
          int index, com.example.demo.protomodel.MusicProto.MusicInfo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.example.demo.protomodel.MusicProto.MusicInfo> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public com.example.demo.protomodel.MusicProto.MusicInfo.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public java.util.List<? extends com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public com.example.demo.protomodel.MusicProto.MusicInfo.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.example.demo.protomodel.MusicProto.MusicInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public com.example.demo.protomodel.MusicProto.MusicInfo.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.example.demo.protomodel.MusicProto.MusicInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .music.MusicInfo items = 1;</code>
       */
      public java.util.List<com.example.demo.protomodel.MusicProto.MusicInfo.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.demo.protomodel.MusicProto.MusicInfo, com.example.demo.protomodel.MusicProto.MusicInfo.Builder, com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.demo.protomodel.MusicProto.MusicInfo, com.example.demo.protomodel.MusicProto.MusicInfo.Builder, com.example.demo.protomodel.MusicProto.MusicInfoOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:music.MusicInfoList)
    }

    // @@protoc_insertion_point(class_scope:music.MusicInfoList)
    private static final com.example.demo.protomodel.MusicProto.MusicInfoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.protomodel.MusicProto.MusicInfoList();
    }

    public static com.example.demo.protomodel.MusicProto.MusicInfoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MusicInfoList>
        PARSER = new com.google.protobuf.AbstractParser<MusicInfoList>() {
      @java.lang.Override
      public MusicInfoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MusicInfoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MusicInfoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.protomodel.MusicProto.MusicInfoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_music_MusicInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_music_MusicInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_music_MusicInfoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_music_MusicInfoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017musicInfo.proto\022\005music\"c\n\tMusicInfo\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\024\n\014artists_name\030" +
      "\003 \001(\t\022\016\n\006picurl\030\004 \001(\t\022\026\n\016music_duration\030" +
      "\005 \001(\t\"0\n\rMusicInfoList\022\037\n\005items\030\001 \003(\0132\020." +
      "music.MusicInfoB)\n\033com.example.demo.prot" +
      "omodelB\nMusicProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_music_MusicInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_music_MusicInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_music_MusicInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "ArtistsName", "Picurl", "MusicDuration", });
    internal_static_music_MusicInfoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_music_MusicInfoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_music_MusicInfoList_descriptor,
        new java.lang.String[] { "Items", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
